# Generated by Django 3.0.8 on 2020-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='image',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='result',
            name='page_number',
        ),
        migrations.AddField(
            model_name='result',
            name='page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
