# Generated by Django 3.0.8 on 2020-08-22 23:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200822_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=500)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
        ),
    ]
