# Generated by Django 3.0.8 on 2020-08-23 05:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_documentpages_positionarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionarray',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=100), size=100),
        ),
    ]
